name: CI

on:
  push:
    branches: [main]

env:
  # coloque aqui o nome do seu bucket
  BUCKET: appreactjs.soaresdev.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # aqui ele pega a versão mais atualizada do código
    - uses: actions/checkout@v2

      # instala a versão do node que você definir
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
     # instala as dependencias do projeto
    - name: Install dependencies
      run: yarn install
    
    # caso sua aplicação possui testes ele executa os testes, caso não tenha comente essa parte.
    # - name: Run tests
    #   run: yarn test --watchAll false
    
    # executa o script de build do projeto
    - name: Build
      run: yarn build
    
    # aqui ele instala a CLI do google cloud plataform dentro do bucket
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    # aqui ele utiliza a CLI do google cloud plataform para copiar o conteudo (build) do projeto para dentro do bucket
    - name: Upload filed to bucket
      run: gsutil -m rsync -R ./build gs://"$BUCKET"
    
    # aqui ele utiliza a CLI do google cloud plataform para dar permissão publica para acesso dos arquivos
    - name: Allow public access
      run: gsutil -m acl ch -R -u AllUsers:R gs://"$BUCKET"
    
    # aqui ele utiliza a CLI do google cloud plataform para setar comandos onde configura o cache de arquivos como imagens e javascript
    - name: Set Cache-Control
      run: gsutil -m setmeta -h "Cache-Control:public, max-age=15768000" gs://"$BUCKET"/**/*.{png,svg,css,js}

    # aqui ele utiliza a CLI do google cloud plataform para setar um comando que faz retirar o cache o arquivo index.html
    - name: Set Cache-Control
      run: gsutil setmeta -h "Cache-Control:no-cache, no-store" gs://"$BUCKET"/index.html
